version: '3.8'
services: 
  sqlserver:
    image: 'mcr.microsoft.com/azure-sql-edge:latest'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "Password1!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"